language: c++
matrix:
  include:
  - os: linux
    before_script:
      - mkdir prebuilts/

      # Download and unzip a recent CMake
      - wget --no-check-certificate https://cmake.org/files/v3.8/cmake-3.8.0-rc2-Linux-x86_64.tar.gz
      - tar xvfz cmake-3.8.0-rc2-Linux-x86_64.tar.gz -C prebuilts/

      # Download and unzip Android NDK
      - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
      - unzip android-ndk-r13b-linux-x86_64.zip -d prebuilts/ > nul

    script:
      - ./call_cmake

      # Take a look at the ELF header
      - readelf -h ~/.hunter/_Base/6974c21/5b02e56/50d56d0/Install/lib/libfreetyped.a | grep 'Class\|File\|Machine'

